slaves:
  hosts:
    slavea:
      ansible_host: 192.168.1.35
      ansible_ssh_user: nfl
    slaveb:
      ansible_host: 192.168.1.34
      ansible_ssh_user: nflb
    slavec:
      ansible_host: 192.168.1.33
      ansible_ssh_user: nfla
masters:
  hosts:
      mastera:
        ansible_host: 192.168.1.43
        ansible_ssh_user: nflc