- hosts: masters
  gather_facts: true
  roles:
    - common
    - bootstrap_swarm_masters
  vars: 
    install_nfs_server_components: true
    install_nfs_client_components: false
- hosts: slaves
  gather_facts: true
  roles:
    - common
    - bootstrap_swarm_slaves
  vars: 
    install_nfs_server_components: false
    install_nfs_client_components: true
- hosts: mastera
  gather_facts: true
  roles:
    - media_server
    - mount_disks
    - create_nfs_share
- hosts: slaves
  gather_facts: true
  roles: 
    - mount_nfs_share