# Mount harddrive
- name: Create folder if not exists
  ansible.builtin.file:
    path: "{{hdd_mount_point}}"
    state: directory
    mode: '0755'
- name: Add fstab entry
  become: true
  ansible.posix.mount:
    path: "{{hdd_mount_point}}"
    src: UUID="{{hdd_uuid}}"
    fstype: ext4
    opts: noatime
    state: present
- name: Mount drive
  ansible.builtin.command: "mount -a"
  become: true