---
# This installs the necessary dependencies.
- name: Update package cache
  ansible.builtin.apt:
    update_cache: yes
    state: fixed
  become: true
- name: Upgrade all packages (safe)
  ansible.builtin.apt:
     upgrade: safe
     state: fixed
  become: true
- name: Install dependencies
  ansible.builtin.apt:
    name: "{{item}}"
    state: present
    update_cache: yes
  loop:
    - python3-pip
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
  become: true
# Install NFS dependencies
- name: Installing NFS server components
  ansible.builtin.apt:
    update_cache: true
    name: nfs-kernel-server
  become: true
  when: install_nfs_server_components
- name: Installing NFS client components
  ansible.builtin.apt:
    update_cache: true
    name: nfs-common
  become: true
  when: install_nfs_client_components