---
# This installs docker.
- name: Add gpg key for docker
  become: true
  ansible.builtin.apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
- name: Add docker repository
  become: true
  apt_repository:
    repo: "deb https://download.docker.com/linux/ubuntu {{ ansible_facts.distribution_release }} stable"
    state: present
- name: Install docker and dependencies
  become: true
  ansible.builtin.apt:
    name: "{{item}}"
    state: present
    update_cache: yes
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin
- name: Install python docker package
  become: true
  ansible.builtin.pip:
    name: "{{item}}"
  loop:
    - jsondiff # Might remove as docker stack is not used anymore
    - docker
    - docker-compose